# \\vboxsvr\vagrant
# https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
# https://github.com/hugsy/modern.ie-vagrant

# I have not been able to get "winrm" to work, and I have no use for it and it does not seem to be possible to make Vagrant skip trying to SSH in to the machine. So just ignore the SSH authentication problems.

# Direct download:
# https://aka.ms/ie11.win7.vagrant

# More:
# https://aka.ms/ie6.xp.vagrant
# https://aka.ms/ie8.xp.vagrant
# https://aka.ms/ie7.vista.vagrant
# https://aka.ms/ie8.win7.vagrant
# https://aka.ms/ie9.win7.vagrant
# https://aka.ms/ie10.win7.vagrant
# https://aka.ms/ie11.win7.vagrant
# https://aka.ms/ie10.win8.vagrant
# https://aka.ms/ie11.win81.vagrant
# https://aka.ms/msedge.win10.vagrant

Vagrant.configure("2") do |config|
  config.vm.hostname = "win7"
  config.vm.box = "win7"
  config.vm.box_url = "IE11 - Win7.box"
  config.vm.guest = :windows
  config.vm.provider "virtualbox" do |v|
    v.gui = true

    # Create a 100 GB extra disk
    # vdi files are easily expandable with:
    # vboxmanage modifyhd data.vdi --resize 500000
    # data_disk = File.expand_path("data.vdi")
    # if !File.exist?(data_disk)
    #   # puts "Creating extra data disk: #{data_disk}"
    #   v.customize ["createhd", "--filename", data_disk, "--format", "VDI", "--size", 100000]
    #   v.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
    # end
    # v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 0, "--device", 0, "--type", "hdd", "--medium", data_disk]
  end
end
