# Delete volumes: (use e.g. when upgrading postgres)
# docker compose down -v

services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgresdata:/var/lib/postgresql/data

  # Default minio credentials: minioadmin/minioadmin
  # Console: http://localhost:9001/
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001
    volumes:
      - miniodata:/data

volumes:
  postgresdata:
    driver: local
  miniodata:
    driver: local
