#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'NixOS' {
    insmod part_gpt
    insmod btrfs
    search --no-floppy --fs-uuid --set=root 1f5ba753-af3e-40e0-9cb2-e9e29fa2a5b8
    configfile /@/boot/grub/grub.cfg
}
